name: Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK 8
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 8
    - name: Gradle Build
      run: gradle build
    - name: Upload distribution archive
      uses: actions/upload-artifact@v2-preview
      with:
        name: open-cue-cli.zip
        path: build/distributions/open-cue-cli.zip
