name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK 8
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 8
      - name: Gradle Build
        run: gradle build
      - name: Generate Bash Completion
        env:
          OPEN_CUE_CLI_COMPLETE: bash
        run: |
          unzip build/distributions/open-cue-cli.zip
          ./open-cue-cli/open-cue-cli > open-cue-cli/bash-complete-open-cue-cli.sh
          chmod +x open-cue-cli/bash-complete-open-cue-cli.sh
      - name: Upload distribution archive
        uses: actions/upload-artifact@v2
        with:
          name: open-cue-cli
          path: open-cue-cli/
