name: Release

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK 8
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 8
      - name: Gradle Build
        run: gradle build
      - name: Generate Bash Completion
        env:
          OPEN_CUE_CLI_COMPLETE: bash
        run: |
          unzip build/distributions/open-cue-cli.zip
          ./open-cue-cli/open-cue-cli > open-cue-cli/bash-complete-open-cue-cli.sh
          chmod +x open-cue-cli/bash-complete-open-cue-cli.sh
          zip open-cue-cli.zip open-cue-cli
      - name: Get upload url
        id: release-id
        run: |
          RELEASE_ID=$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)
          echo "::set-output name=upload_url::https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${RELEASE_ID}/assets{?name,label}"
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release-id.outputs.upload_url }}
          asset_path: open-cue-cli.zip
          asset_name: open-cue-cli.zip
          asset_content_type: application/zip
